'use client';

import { useEffect, useRef, useState } from 'react';
import type { InvestmentDecision } from '@/lib/types';
import dynamic from 'next/dynamic';

// Dynamically import canvas-based chart to avoid SSR issues
const RadarChart = dynamic(() => import('./RadarChart'), { ssr: false });

const WEIGHT_PCT: Record<string, number> = {
  'very high': 95, 'high': 80, 'medium': 55, 'low': 30, 'very low': 15,
};

const VERDICT_META: Record<string, { emoji: string; label: string; color: string }> = {
  invest: { emoji: '🚀', label: 'Strong Buy',   color: '#34d399' },
  pass:   { emoji: '🛑', label: 'Avoid',        color: '#f87171' },
  watch:  { emoji: '👁️', label: 'Monitor',      color: '#fbbf24' },
};

/* ─── Animated counter hook ─────────────────────────── */
function useCounter(target: number, duration = 1200) {
  const [val, setVal] = useState(0);
  const frame = useRef<number>();
  useEffect(() => {
    const start = performance.now();
    const tick = (now: number) => {
      const p = Math.min((now - start) / duration, 1);
      const ease = 1 - Math.pow(1 - p, 3);
      setVal(Math.round(ease * target));
      if (p < 1) frame.current = requestAnimationFrame(tick);
    };
    const id = setTimeout(() => { frame.current = requestAnimationFrame(tick); }, 300);
    return () => { clearTimeout(id); if (frame.current) cancelAnimationFrame(frame.current); };
  }, [target, duration]);
  return val;
}

/* ─── PDF Export ─────────────────────────────────────── */
function handleExportPDF(companyName: string, verdict: string) {
  const ts = new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' });
  const printContent = document.getElementById('verdict-printable');
  if (!printContent) return;

  const w = window.open('', '_blank');
  if (!w) return;
  w.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>InvestorAI – ${companyName} Report</title>
      <meta charset="utf-8">
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 40px; color: #0f0f1a; background: #fff; }
        h1 { font-size: 2rem; font-weight: 900; margin: 0 0 4px; }
        h2 { font-size: 1.1rem; font-weight: 700; margin: 24px 0 12px; border-bottom: 2px solid #e5e7eb; padding-bottom: 8px; }
        .verdict-badge { display: inline-block; padding: 6px 20px; border-radius: 99px; font-weight: 800; font-size: 0.95rem; margin: 8px 0 20px; }
        .invest { background: #d1fae5; color: #065f46; }
        .pass   { background: #fee2e2; color: #991b1b; }
        .watch  { background: #fef3c7; color: #92400e; }
        table { width: 100%; border-collapse: collapse; margin: 12px 0; }
        th { background: #f3f4f6; font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.05em; padding: 8px 12px; text-align: left; }
        td { padding: 10px 12px; border-bottom: 1px solid #e5e7eb; font-size: 0.9rem; }
        .positive { color: #059669; font-weight: 600; }
        .negative { color: #dc2626; font-weight: 600; }
        .neutral  { color: #6b7280; }
        .meta { color: #6b7280; font-size: 0.8rem; margin-bottom: 32px; }
        .summary-box { background: #f8f9fa; border-left: 4px solid #7c3aed; padding: 16px; border-radius: 4px; margin: 12px 0; font-size: 0.95rem; line-height: 1.7; }
        .footer { margin-top: 48px; color: #9ca3af; font-size: 0.78rem; border-top: 1px solid #e5e7eb; padding-top: 16px; }
        .conf { font-size: 3rem; font-weight: 900; color: #7c3aed; }
        .conf-label { color: #6b7280; font-size: 0.8rem; font-weight: 600; }
        .grid2 { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin: 12px 0; }
        .stat-box { background: #f3f4f6; padding: 14px; border-radius: 8px; }
        .stat-key { font-size: 0.72rem; text-transform: uppercase; letter-spacing: 0.07em; color: #6b7280; font-weight: 700; margin-bottom: 4px; }
        .stat-val { font-size: 1.05rem; font-weight: 700; color: #111827; }
        ul { padding-left: 20px; line-height: 1.8; color: #374151; }
      </style>
    </head>
    <body>
      <p class="meta">Generated by InvestorAI · ${ts}</p>
      ${printContent.innerHTML}
      <div class="footer">InvestorAI · Powered by GPT-4o & LangGraph · InsideIIM × Altuni AI Labs · For educational purposes only. Not financial advice.</div>
    </body>
    </html>
  `);
  w.document.close();
  setTimeout(() => { w.print(); }, 400);
}

interface Props {
  decision: InvestmentDecision;
  companyName?: string;
  financialScore?: number;
  newsScore?: number;
  industryScore?: number;
}

export default function VerdictCard({ decision, companyName = 'Company', financialScore, newsScore, industryScore }: Props) {
  const [fillW, setFillW] = useState('0%');
  const count    = useCounter(decision.confidence);
  const verdictKey = decision.verdict.toLowerCase();
  const meta     = VERDICT_META[verdictKey] ?? { emoji: '📊', label: 'Decision', color: '#a78bfa' };

  useEffect(() => {
    const t = setTimeout(() => setFillW(`${decision.confidence}%`), 200);
    return () => clearTimeout(t);
  }, [decision.confidence]);

  // Build radar data from available scores
  const confScore = Math.round(decision.confidence / 10);
  const finScore  = financialScore  ? Math.round(financialScore * 1.1)          : Math.round(confScore * 0.9);
  // newsScore is -1..1, convert to 0-10
  const newsS     = newsScore !== undefined ? Math.round((newsScore + 1) * 5)   : Math.round(confScore * 0.85);
  const indScore  = industryScore   ? Math.round(industryScore * 1.1)           : Math.round(confScore * 0.95);
  const riskScore = decision.riskLevel === 'Low' ? 8 : decision.riskLevel === 'High' || decision.riskLevel === 'Very High' ? 3 : 5;


  const radarData = [
    { label: 'Financials',  value: Math.min(10, finScore) },
    { label: 'Sentiment',   value: Math.min(10, newsS) },
    { label: 'Industry',    value: Math.min(10, indScore) },
    { label: 'Risk',        value: Math.min(10, riskScore) },
    { label: 'Conviction',  value: Math.min(10, confScore) },
  ];

  // Build printable HTML for PDF
  const bullCaseHtml = decision.bullCase.map(b => `<li>${b}</li>`).join('');
  const bearCaseHtml = decision.bearCase.map(b => `<li>${b}</li>`).join('');
  const factorsRows  = decision.keyFactors.map(f => `
    <tr>
      <td style="font-weight:600">${f.factor}</td>
      <td class="${f.impact}">${f.impact === 'positive' ? '↑' : f.impact === 'negative' ? '↓' : '→'} ${f.impact}</td>
      <td>${f.weight}</td>
    </tr>
  `).join('');

  const printableHTML = `
    <h1>${companyName}</h1>
    <span class="verdict-badge ${verdictKey}">${meta.emoji} ${decision.verdict}</span>
    <div style="display:flex;gap:32px;align-items:center;margin-bottom:8px">
      <div><div class="conf-label">AI CONFIDENCE</div><div class="conf">${decision.confidence}%</div></div>
      <div><div class="conf-label">TIME HORIZON</div><div style="font-size:1.1rem;font-weight:700;margin-top:4px">${decision.timeHorizon}</div></div>
      <div><div class="conf-label">RISK LEVEL</div><div style="font-size:1.1rem;font-weight:700;margin-top:4px">${decision.riskLevel}</div></div>
    </div>
    <h2>Summary</h2>
    <div class="summary-box">${decision.summary}</div>
    <div class="grid2">
      <div class="stat-box"><div class="stat-key">Target Price</div><div class="stat-val">${decision.targetPrice}</div></div>
      <div class="stat-box"><div class="stat-key">Current Price</div><div class="stat-val">${decision.currentPrice}</div></div>
    </div>
    <h2>Bull Case</h2>
    <ul>${bullCaseHtml}</ul>
    <h2>Bear Case</h2>
    <ul>${bearCaseHtml}</ul>
    <h2>Key Decision Factors</h2>
    <table>
      <thead><tr><th>Factor</th><th>Impact</th><th>Weight</th></tr></thead>
      <tbody>${factorsRows}</tbody>
    </table>
  `;

  return (
    <div className="verdict-section">
      {/* Hidden div for PDF export */}
      <div id="verdict-printable" style={{ display: 'none' }} dangerouslySetInnerHTML={{ __html: printableHTML }} />

      {/* Eyebrow */}
      <div className="verdict-eyebrow">
        <span className="verdict-eyebrow-label">Final Recommendation</span>
        <div className="verdict-eyebrow-line" />
        <button
          className="pdf-export-btn"
          onClick={() => handleExportPDF(companyName, decision.verdict)}
          title="Export report as PDF"
          id="export-pdf-btn"
        >
          📄 Export PDF
        </button>
        <span className="pill info" style={{ fontSize: '0.7rem' }}>{meta.emoji} AI Generated</span>
      </div>

      <div className={`verdict-card ${verdictKey}`}>
        <div className="verdict-blob" aria-hidden />

        {/* Top — verdict word + confidence */}
        <div className="verdict-row-top">
          <div>
            <div className="verdict-eyebrow-sm">Investment Decision</div>
            <div className="verdict-word">{decision.verdict.toUpperCase()}</div>
            <div style={{ marginTop: 'var(--s3)' }}>
              <span className="verdict-status-badge">
                <span style={{
                  width: 8, height: 8, borderRadius: '50%',
                  background: meta.color,
                  boxShadow: `0 0 8px ${meta.color}`,
                  display: 'inline-block', flexShrink: 0,
                }} />
                {meta.label}
              </span>
            </div>
          </div>

          <div className="verdict-confidence">
            <div className="verdict-conf-label">AI Confidence</div>
            <div className="verdict-conf-num" style={{ color: meta.color }}>
              {count}<span style={{ fontSize: '1.1rem', fontWeight: 500, color: 'var(--text-dim)' }}>%</span>
            </div>
            <div className="verdict-conf-track">
              <div className="verdict-conf-fill" style={{ width: fillW }} />
            </div>
            <div style={{ fontSize: '0.7rem', color: 'var(--text-dim)', marginTop: 4 }}>
              {count >= 80 ? 'High conviction' : count >= 60 ? 'Moderate conviction' : 'Low conviction'}
            </div>
          </div>
        </div>

        {/* Radar Chart + Summary side by side */}
        <div className="verdict-radar-row">
          <div className="verdict-radar-wrap">
            <div className="verdict-radar-label">Score Radar</div>
            <RadarChart data={radarData} size={220} />
          </div>
          <div className="verdict-summary-wrap">
            <div className="verdict-summary">{decision.summary}</div>

            {/* Metrics */}
            <div className="verdict-metrics">
              {[
                { label: 'Target Price',  value: decision.targetPrice },
                { label: 'Current Price', value: decision.currentPrice },
                { label: 'Time Horizon',  value: decision.timeHorizon },
                { label: 'Risk Level',    value: decision.riskLevel },
              ].map(m => (
                <div className="v-stat" key={m.label}>
                  <div className="v-stat-label">{m.label}</div>
                  <div className="v-stat-value"
                    style={m.label === 'Risk Level' ? {
                      color: m.value === 'Low' ? '#10b981' : m.value === 'High' || m.value === 'Very High' ? '#ef4444' : '#f59e0b',
                    } : undefined}
                  >{m.value}</div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Bull / Bear */}
        <div className="bb-grid">
          <div className="bb-panel">
            <div className="bb-head bull">↑ Bull Case</div>
            <ul className="bb-list">
              {decision.bullCase.map((x, i) => (
                <li key={i}><span className="bb-dot bull" />{x}</li>
              ))}
            </ul>
          </div>
          <div className="bb-panel">
            <div className="bb-head bear">↓ Bear Case</div>
            <ul className="bb-list">
              {decision.bearCase.map((x, i) => (
                <li key={i}><span className="bb-dot bear" />{x}</li>
              ))}
            </ul>
          </div>
        </div>

        {/* Key Factors table */}
        <div style={{ position: 'relative', zIndex: 1 }}>
          <div className="divider-label" style={{ marginBottom: 'var(--s4)' }}>
            <span className="divider-label-text">Key Decision Factors</span>
            <span className="divider-label-line" />
          </div>
          <div className="ftable-wrap">
            <table className="ftable">
              <thead>
                <tr>
                  <th>Factor</th>
                  <th>Impact</th>
                  <th>Weight</th>
                </tr>
              </thead>
              <tbody>
                {decision.keyFactors.map((f, i) => {
                  const wpct = WEIGHT_PCT[f.weight?.toLowerCase()] ?? 50;
                  return (
                    <tr key={i}>
                      <td style={{ fontWeight: 600, color: 'var(--text-light)' }}>{f.factor}</td>
                      <td>
                        <span className={`impact-badge ${f.impact}`}>
                          {f.impact === 'positive' ? '↑' : f.impact === 'negative' ? '↓' : '→'} {f.impact}
                        </span>
                      </td>
                      <td>
                        <div className="wbar-row">
                          <span style={{ fontSize: '0.77rem', color: 'var(--text-dim)', minWidth: 40 }}>{f.weight}</span>
                          <div className="wbar-track">
                            <div className="wbar-fill" style={{ width: `${wpct}%` }} />
                          </div>
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
}
